In [3]:
import numpy as np #Подключаем библиотеку


#Создаём различные массивы
TwoD_normal_array = np.array([[0, 1, 2], [3, 4, 5]])
print("Двумерный массив из обычного списка:\n", TwoD_normal_array)

zero_array = np.zeros(3)
print("Массив из нулей:", zero_array)

one_array = np.ones(3)
print("Массив из едениц:", one_array)

arange_array = np.arange(0, 10, 2)
print("Массив созданный arange:", arange_array)
print("------------------------")


#Демонстрируем атрибуты
print("Наш массив:\n", TwoD_normal_array)
print("Форма массива:", TwoD_normal_array.shape)
print("Тип данных:", TwoD_normal_array.dtype)
print("------------------------")


#Примеры индексирования и срезов
print("Наш массив:\n", TwoD_normal_array)
print("Отдельный элемент из 2 строки и 3 столбца:", TwoD_normal_array[1, 2])
print("Извлечённый подмассив:\n", TwoD_normal_array[0:2, 0:2])
print("------------------------")


#Примеры векторных операций и базовых статистик
first_array = np.array([1, 2, 3, 4, 5])
second_array = np.array([10, 20, 30, 40, 50])
print("Наши массивы:\n", first_array, "\n", second_array)

summa = first_array + second_array
print("Сложение наших массивов:", summa)

multiplication = first_array * second_array
print("Произведение наших массивов:", multiplication)

#Базовые статистики первого массива
print("\nНаш массив:", first_array)
print("Среднее значение:", np.mean(first_array))
print("Минимальное значение:", np.min(first_array))
print("Сумма всех элементов:", np.sum(first_array))
print("Медиана:", np.median(first_array))

Двумерный массив из обычного списка:
 [[0 1 2]
 [3 4 5]]
Массив из нулей: [0. 0. 0.]
Массив из едениц: [1. 1. 1.]
Массив созданный arange: [0 2 4 6 8]
------------------------
Наш массив:
 [[0 1 2]
 [3 4 5]]
Форма массива: (2, 3)
Тип данных: int64
------------------------
Наш массив:
 [[0 1 2]
 [3 4 5]]
Отдельный элемент из 2 строки и 3 столбца: 5
Извлечённый подмассив:
 [[0 1]
 [3 4]]
------------------------
Наши массивы:
 [1 2 3 4 5] 
 [10 20 30 40 50]
Сложение наших массивов: [11 22 33 44 55]
Произведение наших массивов: [ 10  40  90 160 250]

Наш массив: [1 2 3 4 5]
Среднее значение: 3.0
Минимальное значение: 1
Сумма всех элементов: 15
Медиана: 3.0
